superfaceai/cli

- README.md
> chore: add build badge

- src/index.ts
- src/logic/index.ts
This PR exports two generate type related functions which are needed in station repository.
> chore: export generate types functions

- fixtures/compiled/strict.suma.ast.json
- package.json
- src/commands/lint.integration.test.ts
- src/logic/lint.test.ts
- yarn.lock
This PRs updates Superface parser dependency and fixes related tests
> chore: update superface parser

- CHANGELOG.md
- package.json
- src/logic/configure.test.ts
- src/logic/configure.ts
This PR fixes [issue 76](https://github.com/superfaceai/cli/issues/76)
> fix: provider name in environment variables

- src/commands/install.ts
- yarn.lock
This PR fixes vulnerabilities found by `yarn audit` and `npm audit`.
> chore: yarn audit fixes

- .github/workflows/release.yml
This PR changes order of operation in release workflow. Project must be built before testing.
> fix: build before test in release workflow

- README.md
This PR adds NPX mention to README
> chore: mention npx

- README.md
- src/commands/install.ts
- src/logic/quickstart.test.ts
- src/logic/quickstart.ts
This PR improves wording in interactive install flow
- [] I have added tests to cover my changes.
> Chore:better wording

- src/commands/interactive.install.integration.test.ts
- src/common/output-stream.ts
- src/logic/quickstart.test.ts
- src/logic/quickstart.ts
This PR adds option to set SDK token during interactive install
> feat: setup sdk token in interactive install

- CHANGELOG.md
- src/logic/generate.test.ts
- src/logic/generate.utils.ts
There was another place where Input and Result types are used
It was broken
> chore: Make generated types more specific

- src/common/output-stream.ts
- src/common/package-manager.test.ts
- src/common/package-manager.ts
- src/logic/quickstart.test.ts
- src/logic/quickstart.ts
- src/logic/quickstart.utils.test.ts
- src/logic/quickstart.utils.ts
This PR adds PackageManager class to work with npm and yarn
> feat: package manager abstraction

- src/commands/interactive.install.integration.test.ts
- src/logic/init.ts
- src/logic/quickstart.test.ts
- src/logic/quickstart.ts
This PR adds ability to install dotenv package during interactive install.
> feat: install dotenv package during interactive install

- src/commands/interactive.install.integration.test.ts
- src/logic/quickstart.test.ts
- src/logic/quickstart.ts
This PR fixes bug in interactive install - last selected provider wasn't installed.
> fix: interactive install last provider selection

- src/commands/install.test.ts
- src/commands/install.ts
- src/commands/lint.ts
- src/logic/install.test.ts
- src/logic/install.ts
- src/logic/lint.ts
- src/logic/quickstart.test.ts
- src/logic/quickstart.ts
- src/logic/quickstart.utils.test.ts
- src/logic/quickstart.utils.ts
- src/test/utils.ts
This PR reactors CLI to compile to cache everywhere.
> Feat: compile to cache in whole cli

- .gitignore
- src/commands/configure.test.ts
- src/commands/configure.ts
- src/commands/install.integration.test.ts
- src/commands/install.test.ts
- src/commands/install.ts
- src/common/profile.ts
- src/logic/configure.test.ts
- src/logic/configure.ts
- src/logic/install.test.ts
- src/logic/install.ts
- src/logic/quickstart.ts
- src/logic/quickstart.utils.test.ts
- src/logic/quickstart.utils.ts
Updates the code that handles transition from local to remote and from remote to local installation in `install` command.
> update install superjson transition

- src/logic/configure.test.ts
- src/logic/configure.ts
Changed configure error message when it couldn't find an installed profile
> fix: configure error message

- .github/workflows/main.yml
- CHANGELOG.md
- src/commands/interactive.install.integration.test.ts
- src/logic/configure.test.ts
- src/test/utils.ts
This PR tries to fix flaky test.
> fix: interactive install test

- CHANGELOG.md
- README.md
- src/commands/generate.integration.test.ts
- src/commands/generate.test.ts
- src/commands/generate.ts
- src/commands/install.integration.test.ts
- src/commands/interactive.install.integration.test.ts
- src/logic/generate.ts
- src/logic/install.test.ts
- src/logic/install.ts
This PR adds generate command to generate types for specific or all the profiles from super.json. PR also removes type generation from install process.
> feat: generate command

- src/commands/create.test.ts
- src/commands/create.ts
This PR removes scope folder creation in project root in cases when user passes specific path where he wants to create files.
> fix: do not create unnecessary scope folder when working with path

- README.md
> fix: remove interactive install mention

- CHANGELOG.md
- src/commands/install.test.ts
- src/commands/install.ts
- src/commands/interactive.install.integration.test.ts
- src/logic/quickstart.test.ts
- src/logic/quickstart.ts
- src/logic/quickstart.utils.test.ts
- src/logic/quickstart.utils.ts
This PR reverts removing of interactive command, interactive install is hidden and to mentioned in readme. 
I misunderstood interactive install point in the pitch document, more info:
https://applifting.slack.com/archives/C013602CL2Y/p1631101897052700
> fix: resurrect interactive install and make it hidden

- CHANGELOG.md
- src/common/index.ts
- src/common/types.ts
- src/logic/configure.ts
- src/logic/configure.utils.test.ts
- src/logic/configure.utils.ts
- src/logic/index.ts
This PR exports function for security values preparation (used during configure) to be used in Air.
> feat: export function for security values preparation

- README.md
- src/commands/publish.ts
Fixes typo in document type argument description.
> Fix typo in documentType description

- CHANGELOG.md
- README.md
- src/commands/check.ts
- src/logic/check.test.ts
- src/logic/check.ts
- src/logic/publish.test.ts
- src/logic/publish.ts
- src/logic/publish.utils.test.ts
- src/logic/publish.utils.ts
This PR add step to check command to check if provider integration parameters are defined in super.json. Also checks if there are unnecessary parameters defined in super.json(produces warning). This check is also done before publishing.
> feat: check integration parameters setup

- src/commands/configure.integration.test.ts
- src/logic/configure.ts
This PR improves messages shown to user when he is configuring provider with integration parameters.
> chore: configure command messages

- package.json
- src/common/http.test.ts
- src/common/http.ts
- src/logic/install.test.ts
- src/logic/install.ts
- src/logic/lint.ts
- src/logic/publish.utils.test.ts
- src/logic/publish.utils.ts
- src/test/utils.ts
- yarn.lock
This PR updates service client and uses it's helpers instead of only `fetch`.
> chore: update service client

- src/commands/lint.integration.test.ts
- src/commands/lint.test.ts
- src/commands/lint.ts
- src/logic/lint.test.ts
- src/logic/lint.ts
This PR refactors Lint command - improves JSON formatting and making the code less confusing.
> chore: refactor lint command

- fixtures/providers/empty.json
- fixtures/providers/provider-without-security.json
- src/commands/configure.integration.test.ts
- src/commands/configure.test.ts
- src/commands/configure.ts
- src/commands/install.integration.test.ts
- src/commands/install.test.ts
- src/commands/install.ts
- src/common/messages.ts
- src/logic/configure.utils.test.ts
- src/logic/configure.utils.ts
This PR adds missing compatibility check during `configure` and `install` command.
> fix: missing check

- .github/workflows/release.yml
After publishing new release (not pre or rc), it will trigger workflow of https://github.com/superfaceai/superface-daily to verify nothing broke.
To automate what we do manually anyway.
> Trigger daily test after publishing new release

- .github/workflows/release.yml
- src/logic/configure.test.ts
> feat: release rc from dev

- CHANGELOG.md
- src/commands/configure.test.ts
- src/commands/configure.ts
- src/commands/install.test.ts
- src/commands/install.ts
- src/common/document.test.ts
- src/common/document.ts
- src/logic/configure.ts
- src/logic/install.test.ts
- src/logic/install.ts
> chore: prepare for release

- CHANGELOG.md
- package.json
> chore: merge main to dev after release

- README.md
- src/commands/compile.ts
Adds `superface compile` into README, and updates typos + language fixes (commas, wording) in its description.
> Chore: README update

- package.json
- yarn.lock
> chore: update sdk version

- src/templates/prepared-map/map-templates/parameters.ts
Fixes: https://github.com/superfaceai/cli/issues/243
> fix: missing back ticks

- src/logic/prepare/mock-map-test.ts
- src/logic/prepare/test.ts
- src/templates/prepared-test/prepare-test.ts
- src/templates/prepared-test/test-templates/test.ts
This PR fixes test template when flag `station` is used. It adds use of `buildSuperfaceTest` helper. Result looks like this: 
```
import { SuperfaceTest } from '@superfaceai/testing';
import { buildSuperfaceTest } from '../../../test-config';
describe('sw/character/unverified-sw', () => {
let superface: SuperfaceTest;
beforeEach(() => {
superface = buildSuperfaceTest({
profile: 'starwars/character-information',
provider: 'swapi',
});
});
describe('Character', () => {
// specify test case name
it('should map error', async () => {
const result = await superface.run({
useCase: 'Character',
input: {
characterName : 'madeUp',
}
})
expect(() => result.unwrap()).toThrow();
expect(result).toMatchSnapshot();
});
// specify test case name
it('should perform successfully', async () => {
const result …
```
> fix: test template

- src/logic/prepare/mock-map-test.ts
- src/templates/prepared-test/test-templates/test.ts
> fix: generated test template

- src/common/messages.ts
- src/logic/prepare/map.ts
- src/logic/prepare/mock-map-test.ts
- src/logic/prepare/mock-map.ts
- src/logic/prepare/profile.ts
- src/logic/prepare/test.ts
This PR improves prepare command success messages with hinting user which command he should use next.
> chore: prepare messages

- package.json
- yarn.lock
> chore: sdk update

- README.md
- src/commands/prepare/map.test.ts
- src/commands/prepare/map.ts
- src/logic/prepare/map.test.ts
- src/logic/prepare/map.ts
- src/templates/prepared-map/map-templates/header.ts
- src/templates/prepared-map/prepare-map.ts
This PR adds `variant` flag to prepare map command.
> feat: prepare map variant

- fixtures/compiled/with-examples.supr.ast.json
- fixtures/with-examples.supr
- src/templates/prepared-map/prepare-mock-map.ts
- src/templates/prepared-map/usecase/example/build.test.ts
- src/templates/prepared-map/usecase/example/build.ts
- src/templates/prepared-map/usecase/prepare-usecase-detail.test.ts
- src/templates/prepared-map/usecase/prepare-usecase-detail.ts
- src/templates/prepared-map/usecase/usecase.ts
- src/templates/prepared-test/test-templates/error.ts
- src/templates/prepared-test/test-templates/success.ts
- src/templates/prepared-test/test-templates/test.ts
- src/templates/prepared-test/test-templates/usecase.ts
This PR adds ability to use all of the profile examples as test cases in generated test. We are still able to fall back to generated examples from type definitions.
> feat: multiple examples in prepare test

- src/logic/create/provider/parameters.test.ts
- src/logic/create/provider/parameters.ts
This PR fixes problem with infinite loop during provider create
> fix: provider create loop

- src/templates/prepared-map/usecase/prepare-input-scalar.test.ts
- src/templates/prepared-map/usecase/prepare-input-scalar.ts
This PR fixes problem with empty example during map generation
> fix: missing empty check

- src/commands/new.test.ts
- src/commands/new.ts
- src/common/messages.ts
- src/logic/new.test.ts
- src/logic/new.ts
This PR adds `new` command for profile preparation.
> feat: new command

- src/common/error.test.ts
- src/common/error.ts
This PR adds util to stringify Error instances
> feat: stringify error util

- src/commands/map.test.ts
- src/commands/map.ts
- src/logic/application-code/application-code.test.ts
- src/logic/application-code/application-code.ts
This PR adds usage of application code preparation to map command
> feat: use application code writer

- src/common/polling.test.ts
- src/common/polling.ts
This PR fixes polling status enum.
> fix: polling status enum

- src/common/polling.test.ts
- src/common/polling.ts
This PR fixes polling error messages. Polling is shared with `prepare`, `new` and `map` commands.
> fix: polling error messages

- src/commands/map.ts
This PR adds saving of prepared boilerplate code.
> feat: save boilerplate

- src/commands/map.test.ts
- src/commands/map.ts
- src/common/file-structure.ts
- src/common/messages.ts
- src/logic/project/index.ts
- src/logic/project/js.test.ts
- src/logic/project/js.ts
This PR adds helper function to prepare package.json file in superface folder to use generated integration.
Helper function is used in map command.
> feat: prepare package json

- src/commands/map.test.ts
- src/commands/map.ts
- src/logic/application-code/application-code.test.ts
- src/logic/application-code/js/application-code.ts
This PR fixes problem with incorrect location of application code and updates application code template to be aligned with OneSdk examples
> fix: application template

- src/commands/execute.ts
- src/common/ux.ts
This PR fixes problem with spinner graphics blinking on some monitors. Now we update text only if it is changed and also time between rendering is lower.
> fix: spinner blinking

- src/commands/prepare.ts
> Fix: typo in prepare next step example

- src/commands/execute.ts
- src/commands/map.ts
- src/commands/new.ts
- src/common/file-structure.test.ts
- src/common/file-structure.ts
- src/logic/application-code/application-code.test.ts
- src/logic/application-code/js/application-code.ts
- src/logic/new.test.ts
- src/logic/new.ts
This PR updates profile id related code to be able to handle both formats of profile id. 
CLI also can handle both formats of id in response from authoring API.
> fix: profile id interpretation

- README.md
- src/commands/execute.ts
- src/commands/map.ts
- src/commands/new.ts
- src/commands/prepare.ts
This PR adds basic description of each command
> chore: command description

- src/logic/application-code/application-code.test.ts
- src/logic/application-code/js/application-code.ts
This PR removes `env` property from OneClient constructor in application code template
> chore: remove env from js application code

- .github/ISSUE_TEMPLATE/FEEDBACK_TEMPLATE.md
This PR adds a new issue template.
> Added "feedback" issue template

- src/commands/map.test.ts
- src/commands/map.ts
- src/commands/new.ts
- src/commands/prepare.ts
- src/logic/project/js/js.test.ts
- src/logic/project/js/js.ts
- src/logic/project/prepare-project.ts
- src/logic/project/python/python.test.ts
- src/logic/project/python/python.ts
This PR fixes some minor UX problems- maily adds details about location of created files.
> fix: basic ux fixes

- src/logic/map.test.ts
- src/logic/map.ts
- src/logic/new.test.ts
- src/logic/new.ts
- src/logic/prepare.test.ts
- src/logic/prepare.ts
This PR fixes not helpful message when user tries to use Authoring API without being logged.
> fix: unauthorized error message

- src/common/polling.ts
This PR increases polling timeout to 5 minutes.
> chore: increase polling timeout

- src/logic/application-code/js/application-code.test.ts
- src/logic/application-code/js/application-code.ts
This PR updates JS boilerplate with better error handling. Wait for OneSdk beta.1
> chore: update js boiler plate

- src/logic/application-code/js/application-code.test.ts
- src/logic/application-code/js/application-code.ts
Updates JS boilerplate.
Take more advantage of using ECMAScript modules.
Relates to https://github.com/superfaceai/one-sdk/pull/71
> Update JS boilerplate not to use main function

- src/logic/execution/execute.ts
Mutes warning about WASI being an experimental feature
Execute command will look cleaner.
> Mute Warnings

- src/commands/map.test.ts
- src/commands/map.ts
- src/commands/new.ts
- src/commands/prepare.ts
- src/common/format.test.ts
- src/common/format.ts
- src/logic/application-code/dotenv/dotenv.test.ts
- src/logic/application-code/dotenv/dotenv.ts
- src/logic/application-code/dotenv/onesdk-token.ts
- src/logic/application-code/js/application-code.test.ts
- src/logic/application-code/js/application-code.ts
- src/logic/application-code/python/application-code.test.ts
- src/logic/application-code/python/application-code.ts
- src/logic/project/js/js.test.ts
- src/logic/project/js/js.ts
- src/logic/project/prepare-project.ts
- src/logic/project/python/python.test.ts
- src/logic/project/python/python.ts
- When provider requires attention
- When provider is successfuly created
- With envs in `.env`
- Without envs in `.env` (unauthenticated API or subsequent `map` calls when env was already in .env)
- for Python
- for JS
- for Python
Make the interaction with the CLI easier for our users.
> feat: Updating copy of the commands

- src/logic/application-code/dotenv/dotenv.test.ts
- src/logic/application-code/js/application-code.test.ts
- src/logic/application-code/js/application-code.ts
- src/logic/new.ts
> fix: missing semicolon in js boilerplate

- src/commands/execute.test.ts
- src/commands/execute.ts
- src/commands/map.test.ts
- src/commands/map.ts
- src/commands/new.test.ts
- src/commands/new.ts
- src/common/provider.test.ts
- src/common/provider.ts
Fixes: https://github.com/superfaceai/cli/issues/340
Also fixes other commands with two positional arguments where one missing argument can lead to not relevant error message
> fix: checking of arguments

- src/commands/map.test.ts
- src/commands/map.ts
- src/logic/map.test.ts
- src/logic/map.ts
This PR updates map generation endpoint to `/authoring/maps`.
CLI part of: https://www.notion.so/superface/Return-to-profile-ID-conventions-b77f7bfc2fdd40b590f9fcc629b61b27
Waiting on Brain
> [WIP]fix: map generation endpoint

- README.md
- src/commands/new.test.ts
- src/commands/new.ts
- src/logic/new.test.ts
- src/logic/new.ts
This PR adds optional argument profile id to `new` command. This id can be used to override generated id.
Waiting on Brain
> feat: custom profile id

- src/logic/application-code/python/application-code.test.ts
- src/logic/application-code/python/application-code.ts
This PR updates error handling in Python boilerplate code
> fix: python boilerplate code

- src/commands/prepare.test.ts
- src/commands/prepare.ts
This PR fixes problem with preparation of integration from file with structured text and upper case name.
Detected by Lukas V.
> fix: provider name from filename

- README.md
- src/commands/execute.ts
- src/commands/map.ts
This PR uncovers hidden optional argument `language` in `map` and `execute` commands.
> chore: show optional language argument

- src/commands/map.ts
- src/commands/new.ts
- src/commands/prepare.ts
Solves: https://github.com/superfaceai/cli/issues/345
> chore: highlight command print outs

- package.json
This PR adds `postinstall` script package.json.
Another way to do this would be to have custom script 🤷🏻‍♂️
> chore: postinstall

- CHANGELOG.md
- src/logic/application-code/js/application-code.test.ts
- src/logic/application-code/js/application-code.ts
- src/logic/application-code/python/application-code.test.ts
- src/logic/application-code/python/application-code.ts
OneClient will throw ValidationError on invalid user inputs. This PR updates generated app code to reflect it.
https://github.com/superfaceai/one-sdk/pull/90
Plus updated formatting of python code as said in [PEP8](https://peps.python.org/pep-0008/#indentation).
> Update generated app code with ValidationError

- CHANGELOG.md
- src/common/messages.ts
> chore: update changelog

- CHANGELOG.md
- src/logic/application-code/js/application-code.test.ts
- src/logic/application-code/js/application-code.ts
Updates application code template for Node.js accroding to new package structure.
With older import it won't work. :)
> New import for OneSDK in app code templates

- CHANGELOG.md
- src/common/error.ts
> fix: double error message

- src/commands/prepare.test.ts
- src/commands/prepare.ts
- src/common/polling.ts
- src/logic/prepare.test.ts
- src/logic/prepare.ts
This PR adds force flag to prepare command, this flag allows reindexing of existing provider
> feat: prepare force flag
