CHANGELOG.md, fixtures/install/playground/superface/types/starwars/character-information.ts, src/common/http.ts, src/logic/generate.ts, src/logic/generate.utils.ts
Instead of generating an interface for Result, generates type alias that can take any shape
Only object results were supported so far
=> feat(generate): Allow every type for Result

README.md, src/commands/install.test.ts, src/commands/install.ts
This PR adds parsing of coma (only coma not space) separated provider names
=> fix: coma separated providers

src/commands/init.integration.test.ts, src/commands/play.integration.test.ts, src/logic/init.test.ts, src/logic/init.ts, src/logic/quickstart.ts, src/templates/init.ts
This PR removes generation of gitignore file and build folder during superface init.
=> chore: do not generate build folder and gitignore

src/logic/generate.test.ts, src/logic/generate.ts, src/logic/generate.utils.ts
Makes generated types specific to both profile and usecase
Generated types were specific only to usecase -> there were conflicts when two profiles had the same usecase name
=> chore: Make generated types more specific

src/commands/interactive.install.integration.test.ts, src/common/package-manager.test.ts, src/common/package-manager.ts, src/logic/quickstart.test.ts, src/logic/quickstart.ts
This PR fixes problems with package manager during interactive install.
Test are coming.
Logic behind PM resolution:
if we don't find the package.json we ask user to select npm, yarn or exit.This information is used to init selected PM, selected PM is saved on PM static side.After init we try to install packages:
we use PM saved in PM, if undefined we try to find out used PM, if undefined we use NPM.
=> fix: package manager resolution

package.json, src/commands/check.test.ts, src/commands/check.ts, src/commands/compile.test.ts, src/commands/compile.ts, src/commands/configure.integration.test.ts, src/commands/create.integration.test.ts, src/commands/interactive.create.integration.test.ts, src/commands/lint.test.ts, src/commands/lint.ts, src/logic/configure.test.ts, src/logic/configure.ts, src/logic/create.test.ts, src/logic/create.ts, src/logic/install.test.ts, src/logic/install.ts, src/logic/quickstart.ts, yarn.lock
Updates to newer one-sdk version
Updates superjson mutate method calls
Update configure transition so it uses `set` mutate methods
Added reconfigure methods
- [] Bug fix (non-breaking change which fixes an issue)
=> update mutate methods with new one-sdk version

src/common/document.test.ts, src/common/document.ts, src/logic/install.test.ts, src/logic/install.ts
This PR refactors document file and updates install to use Parser to cache for parsing. Only command not using Parser to cache is Lint.
=> feat: parse to cache

CHANGELOG.md, README.md, src/commands/create.integration.test.ts, src/commands/create.test.ts, src/commands/create.ts, src/commands/interactive.create.test.ts, src/logic/create.test.ts, src/logic/create.ts, src/logic/init.test.ts, src/logic/init.ts
This PR adds flags for specifying name of crated file when creating map/profile/provider
This change is needed to enable CLI usage in Station.
=> feat: create command file name flags

CHANGELOG.md, src/commands/compile.test.ts, src/commands/compile.ts
This PR fixes wrong identifier use in compile command.
=> fix: compile provider name check

src/commands/lint.test.ts, src/commands/lint.ts
This PR removes throwing error on lint warning.
=> fix: do not throw on lint warning

src/commands/install.test.ts, src/commands/install.ts
This PR removes printing "Configuring providers" during install command when there are no providers to configure.
=> fix: print message only when there are some providers to configure

src/commands/install.test.ts, src/commands/install.ts, src/logic/install.test.ts, src/logic/install.ts
This PR fixes problems with loading invalid super.json during install command.
=> fix: install command sj load

src/commands/configure.test.ts, src/commands/configure.ts, src/common/document.test.ts, src/common/document.ts, src/logic/configure.ts
This PR adds `mapVariant` option to `configure` command. 
Example:
`superface configure twilio -p send-sms --mapVariant generated`
Interaction designer creates maps with variant set to `generated` and we need to support configuration of such maps.
I did not implement validation of the `mapVariant` flag against Superface registry when running install command.
This is the error message user gets with first perform when invalid map variant is configured:
=> Add `mapVariant` option to `configure` command

src/commands/init.integration.test.ts, src/common/document.ts, src/logic/init.test.ts, src/logic/init.ts
This PR removes creation of superface/grid and superface/type folders during Init command call.
=> chore: update init command

src/commands/compile.test.ts, src/commands/compile.ts, src/logic/compile.test.ts, src/logic/compile.ts
This pr simplifies compile command logic. Instead of nested object array, flat array is passed (representing files to be compiled). `Kind` of each element is used to decide if we are compiling profile or map. Pr also simplifies filtering of map/profiles when onlyMaps/onlyProfiles flag is used. This does not change API for user. 
fixes: https://github.com/superfaceai/cli/issues/222
=> chore: compile command refactor

src/commands/lint.ts, src/logic/lint.test.ts, src/logic/lint.ts
This PR fixes: https://github.com/superfaceai/cli/issues/238 by adding instances check and fallback to userError
=> chore: improve lint type safety

src/templates/prepared-map/map-templates/http.ts, src/templates/prepared-map/prepare-map.ts
This PR adds provider base url value to comment right above HTTP call in map template. It should help users with using right url in HTTP calls
=> feat: add base url to template

CHANGELOG.md, README.md, src/commands/prepare/mock-map-test.test.ts, src/commands/prepare/mock-map-test.ts, src/common/messages.ts, src/logic/prepare/mock-map-test.test.ts, src/logic/prepare/mock-map-test.ts, src/logic/prepare/test.ts, src/templates/prepared-test/prepare-test.ts, src/templates/prepared-test/test-templates/test.ts, src/templates/prepared-test/test-templates/usecase.ts
This PR adds command `prepare:mock-map-test` which generates test for map with mock provider. This file should match generated mock provider map (always return success example)
Half of the changes is formatting of commands in README by new version of oclif CLI.
=> feat: prepare mock map test

src/logic/prepare/mock-map-test.ts, src/templates/prepared-map/map-templates/any.ts, src/templates/prepared-map/map-templates/index.ts, src/templates/prepared-map/map-templates/list.ts, src/templates/prepared-map/map-templates/object.ts, src/templates/prepared-map/map-templates/unknown.ts, src/templates/prepared-map/usecase/get-list-details.ts, src/templates/prepared-map/usecase/get-object-details.ts, src/templates/prepared-map/usecase/get-type-details.ts
This PR fixes map preparation in cases when profile does do define exact type of field - types in profile are optional according to spec.  
Problematic (now fixed) expressions: 
```
input {
title!
detail
m!
t [z]
}
```
=> fix: undefined type in profile

src/templates/prepared-map/map-templates/enum.ts, src/templates/prepared-map/map-templates/list.ts, src/templates/prepared-map/map-templates/object.ts
This PR fixes problem with rendering array of enum values in map.
=> fix: map generation array of enums

CHANGELOG.md, package.json, src/commands/whoami.integration.test.ts, src/common/http.test.ts, src/test/utils.ts, yarn.lock
This PR updates @superfaceai/service-client to v5.2.1 with fixed getProvidersList, getProvider and getUserInfo methods which did not set `Accept` header.
Upcoming versions of Superface services API will not accept request without `Accept` header set.
=> Update @superfaceai/service-client to v5.2.1

src/commands/map.test.ts, src/commands/new.test.ts, src/commands/new.ts, src/commands/prepare.ts
This PR adds check of provider state:
If server returns empty ProviderJson user will get warn message 
If user tries to use empty ProviderJson in new or map command he will get error pointing to provider json.
=> feat: provider state checks

LICENSE, README.md
Updating CLI README, [preview in branch](https://github.com/superfaceai/cli/tree/feat/x-new-readme#readme):
=> feat: README update

src/commands/execute.test.ts, src/commands/map.test.ts, src/commands/map.ts, src/commands/new.test.ts, src/commands/new.ts, src/common/file-structure.ts, src/logic/project/js/js.test.ts
This PR allows CLI to locate local files even when user is in Superface folder. This is useful when running execute command after dependencies installation.
=> fix: path checking

README.md, src/commands/execute.test.ts, src/commands/execute.ts, src/common/file-structure.ts
This PR adds check that throws error when `execute` command is not run from superface directory.
=> feat: execute location check

src/logic/project/js/js.ts
The OneSDK dependency for JS boilerplate project uses `beta` version tag. This way always the latest beta will get installed.
=> feat: Using `beta` tag for JS OneSDK dependency

src/commands/map.test.ts, src/commands/map.ts, src/common/file-structure.test.ts, src/common/file-structure.ts, src/logic/application-code/dotenv/dotenv.test.ts, src/logic/application-code/dotenv/dotenv.ts, src/logic/application-code/dotenv/index.ts, src/logic/application-code/index.ts
This PR adds generation of `.env` file after the boilerplate code is generated (both JS and Python). The `.env` contains provider integration params and security scheme variables that are expected in the application code.
It respects potential previous `.env` file in that it only adds variables that are missing in the previous `.env.
You can go through commit by commit.
Tasks:
=> feat: Boilerplate code inits `.env` file

src/commands/map.test.ts, src/commands/map.ts, src/common/http.test.ts, src/common/http.ts, src/logic/application-code/dotenv/dotenv.test.ts, src/logic/application-code/dotenv/dotenv.ts, src/logic/application-code/dotenv/index.ts, src/logic/application-code/dotenv/onesdk-token.ts, src/logic/application-code/js/application-code.test.ts, src/logic/application-code/js/application-code.ts, src/logic/application-code/python/application-code.test.ts, src/logic/application-code/python/application-code.ts
This PR adds automatic pre-fill of OneSDK token when the boilerplate code is generated in `map` command.
You can go through commit by commit.
Tasks:
Having the token set by default enables our users to see their usage in the application dashboard.
=> feat: Use OneSDK token in the boilerplate code

package.json, src/hooks/init.ts
Removing extension of userAgent (version string) with OneSDK and Parser dependencies version.
```
@superfaceai/cli/4.0.0-beta.12 darwin-arm64 node-v20.4.0 (with @superfaceai/one-sdk@2.4.2, @superfaceai/parser@2.1.0)
```
is now
```
@superfaceai/cli/4.0.0-beta.12 darwin-arm64 node-v20.4.0
```
Having the OneSDK and Parser dependencies version printed out after `--version` is confusing to the users of the upcoming CLI. Those dependencies are there for the older commands, most likely to be removed soon.
=> chore: Remove userAgent extension in init hook

src/commands/execute.ts, src/commands/map.ts
This PR fixes example of `superface execute` command that is printed as a guide after `map` is done so that it respects the selected language.
**When language for `map` was NOT explicitly selected**
- `superface map <provider> <profileId>`, the user gets `superface execute <provider> <profileId>` 
**When language for `map` was explicitly selected**
- `superface map <provider> <profileId> python`, the user gets `superface execute <provider> <profileId> python` 
- `superface map <provider> <profileId> js`, the user gets `superface execute <provider> <profileId> js` 
**This doesn't touch the actual language switching logic, just CLI output for better DX**
=> chore(map): Guide for `execute` respects selected language

src/logic/application-code/dotenv/dotenv.test.ts, src/logic/application-code/dotenv/dotenv.ts
Fixing `dotenv` utility so that it doesn't create duplicate env variables in `.env`.
The first commit is just refactoring of the test code. Easier to review just the second commit.
When provider has >1 security schemes of same type (or same-named parameters but that shouldn't happen), env vars are added to `.env` multiple times.
```json
{
"name": "hubspot",
"defaultService": "default",
"parameters": [],
"services": [
{
"baseUrl": "https://api.hubapi.com/",
"id": "default"
}
],
"securitySchemes": [
{
"type": "apiKey",
"name": "private-app-legacy",
"in": "header",
"id": "private_apps_legacy"
},
{
"type": "apiKey",
"name": "private-app",
"in": "header",
"id": "private_apps"
}
]
}
```
creates the following .env
```env
HUBSPOT_API_KEY=
HUBSPOT_API_KEY=
```
=> fix: `.env` doesn't contain duplicate variables

src/commands/prepare.ts, src/common/chalk-template.ts, src/common/ux.ts
When `prepare` ends in the state when Provider JSON definition needs manual editing, we're printing more attention grabbing message.
Changes made:
- using more saturated orange-y color for warnings (works well on both black & white backgrounds)
- added [templating](https://www.npmjs.com/package/chalk-template) for terminal outputs
- changed the warning message
We felt that the previous message warning felt chatty, not so readable and not grabbing the attention enough. This was problematic because if you overlooked this message and didn't update Provider JSON, the subsequent work goes downhill.
=> feat: Better [ACTION REQUIRED] warning

.github/pull_request_template.md, CONTRIBUTING.md, README.md
- Link to GH Discussions instead of Discord
- Rename CONTRIBUTION_GUIDE.md to CONTRIBUTING.md and related references, since the latter name is standardized.
=> docs: Replace Discord refs w/ GH Discussions, rename CONTRIBUTION_GUIDE

src/common/file-structure.ts, src/logic/application-code/js/application-code.test.ts, src/logic/application-code/js/application-code.ts
This PR fixes two issues with path when using CLI on Windows:
Invalid use of `/` in check was replaced with `path.basename`
Windows \ are now escaped in `assetsPath` in .mjs file template
=> fix: path escaping

src/commands/prepare.test.ts, src/logic/application-code/dotenv/dotenv.test.ts, src/logic/application-code/dotenv/dotenv.ts, src/logic/application-code/dotenv/onesdk-log.ts
Adds ONESDK_LOG= env variable to generated .env file with default value "off"
https://github.com/superfaceai/cli/issues/355
=> feat: one sdk log env

src/commands/prepare.test.ts, src/logic/new.ts
This PR adds printing out of profile source in cases when CLI is not able to parse it, this allows for easier debug.
=> chore: print source in error

CHANGELOG.md, src/common/polling.test.ts, src/common/polling.ts
This PR adds retry of polling of job status. This helps with `SOCKET_CONNECTION_TIMEOUT` breaking long running authoring process. Default value is 3 retries.
=> feat: poll url retry

README.md, src/commands/prepare.test.ts, src/commands/prepare.ts, src/logic/prepare.test.ts, src/logic/prepare.ts
This PR adds optional `printDocs` flag that prints overview of indexed documentation chunks. This can be useful for debugging.
Output looks like this:
=> feat: verbose flag
